name: Angular 17 - CI/CD com Verificação de Sintaxe

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        run: npm test

      - name: Build production
        run: npm run build:prod

      - name: Exibir erros de sintaxe
        if: ${{ failure() }}
        run: echo "Erros de sintaxe encontrados!"
